apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sa.yaml
  - deployment.yaml
  - service.yaml
  - mapping.yaml
commonLabels:
  app: authn
configMapGenerator:
- name: authn-config
  literals:
  - PORT=8080
  - LOGIN_PATH=/anon/login
