apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authn
  name: authn
  namespace: di
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authn
  template:
    metadata:
      labels:
        app: authn
    spec:
      serviceAccountName: authn
      containers:
      - image: jasonblanchard/di-authn
        name: authn
        envFrom:
          - configMapRef:
              name: authn-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        ports:
          - containerPort: 8080

