apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: di
resources:
- sa.yaml
- deployment.yaml
- service.yaml
- mapping.yaml
images:
- name: jasonblanchard/di-auth
  newTag: latest
configMapGenerator:
- literals:
  - PORT=8080
  - NATS_HOST=nats://nats:4222
  name: auth-config
