apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
  namespace: di
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: auth
  type: ClusterIP
